name: ci-09

on:
  push:
    paths:
      - "09/**"
      - ".github/workflows/ci-09.yml"
  pull_request:
    paths:
      - "09/**"
      - ".github/workflows/ci-09.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "09"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r dev_requirements.txt
      - name: Lint
        run: ruff check .
      - name: Tests
        run: pytest
